# Example configuration for the standalone podio timeslice merger
output_file: merged_timeslices.root
max_events: 100
time_slice_duration: 20.0
bunch_crossing_period: 10.0
introduce_offsets: true
merge_mode: edm4hep  # "edm4hep" for hit collections, "edm4eic" for MCParticles and Vertices
sources:
  - input_files:
      - input3.root
      - input3.root
    static_number_of_events: false
    mean_event_frequency: 1.0
    use_bunch_crossing: true
    generator_status_offset: 0
  - input_files:
      - input3.root
    static_number_of_events: true
    static_events_per_timeslice: 1
    use_bunch_crossing: true
    generator_status_offset: 1000
