# Example configuration for the standalone podio timeslice merger
output_file: merged_timeslices.root
max_events: 100
time_slice_duration: 2000.0 # in ns
bunch_crossing_period: 40.0 # in ns
introduce_offsets: true
sources:
  - name: signal
    input_files:
      - input3.root    
    static_number_of_events: true
    static_events_per_timeslice: 1
    use_bunch_crossing: true
    generator_status_offset: 0
  - name: minbias
    input_files:
      - input3.root    
    static_number_of_events: false
    mean_event_frequency: 0.000083 # in GHz
    use_bunch_crossing: true
    generator_status_offset: 0
  - name: bethe_heitler
    input_files:
      - input3.root    
    static_number_of_events: false
    mean_event_frequency: 1.8 # in GHz # Check value
    use_bunch_crossing: true
    generator_status_offset: 0
  - name: hadron_beamgas
    input_files:
      - input3.root
    static_number_of_events: false
    mean_event_frequency: 0.0000225 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: 0.025 # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.030 # in ns
    generator_status_offset: 0
  - name: electron_beamgas_bremsstrahlung
    input_files:
      - input3.root
    static_number_of_events: false
    mean_event_frequency: 0.00031694 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: -pi # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.003 # in ns
    generator_status_offset: 0
  - name: electron_beamgas_coulomb
    input_files:
      - input3.root
    static_number_of_events: false
    mean_event_frequency: 0.00000086 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: -pi # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.003 # in ns
    generator_status_offset: 0
  - name: electron_beamgas_touschek
    input_files:
      - input3.root
    static_number_of_events: false
    mean_event_frequency: 0.00000055 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: -pi # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.003 # in ns
    generator_status_offset: 0
  - name: electron_synchrotron
    input_files:
      - input3.root
    static_number_of_events: false
    mean_event_frequency: 3.324 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: -pi # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.003 # in ns
    generator_status_offset: 0
