name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eic/eic_ci:nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup EIC Environment
        run: |
          # Check if cmake is available
          which cmake || echo "CMAKE NOT FOUND"
          cmake --version || echo "CMAKE VERSION ERROR"
          
          # Source any available environment setup scripts
          if [ -f "/opt/detector/setup.sh" ]; then
            echo "Sourcing /opt/detector/setup.sh"
            source /opt/detector/setup.sh
          else
            echo "/opt/detector/setup.sh not found"
          fi
          
          if [ -f "/opt/software/setup.sh" ]; then
            echo "Sourcing /opt/software/setup.sh"
            source /opt/software/setup.sh
          else
            echo "/opt/software/setup.sh not found"
          fi
          
          if [ -f "/usr/local/bin/thisroot.sh" ]; then
            echo "Sourcing ROOT setup"
            source /usr/local/bin/thisroot.sh
          else
            echo "ROOT setup not found at /usr/local/bin/thisroot.sh"
          fi
          
          # Set up common EIC paths
          export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          
          # Print environment for debugging
          echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "PATH: $PATH"
          
          # Check for available packages
          echo "=== Searching for podio and edm4hep packages ==="
          find /usr/local -name "*podio*" -o -name "*edm4hep*" 2>/dev/null | head -10 || echo "No podio/edm4hep found in /usr/local"
          find /opt -maxdepth 3 -name "*podio*" -o -name "*edm4hep*" 2>/dev/null | head -10 || echo "No podio/edm4hep found in /opt"
          
          # Check for CMake configuration files
          echo "=== Searching for CMake config files ==="
          find /usr -name "*podio*.cmake" -o -name "*EDM4HEP*.cmake" 2>/dev/null | head -5 || echo "No CMake config files found"
          
          # Try to find pkg-config files
          echo "=== Searching for pkg-config files ==="
          find /usr -name "*podio*.pc" -o -name "*edm4hep*.pc" 2>/dev/null | head -5 || echo "No pkg-config files found"

      - name: Configure
        run: |
          # Source environment again to ensure variables persist
          if [ -f "/opt/detector/setup.sh" ]; then source /opt/detector/setup.sh; fi
          if [ -f "/opt/software/setup.sh" ]; then source /opt/software/setup.sh; fi
          if [ -f "/usr/local/bin/thisroot.sh" ]; then source /usr/local/bin/thisroot.sh; fi
          export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          
          echo "Configuring with cmake..."
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build
        run: |
          # Source environment again
          if [ -f "/opt/detector/setup.sh" ]; then source /opt/detector/setup.sh; fi
          if [ -f "/opt/software/setup.sh" ]; then source /opt/software/setup.sh; fi
          if [ -f "/usr/local/bin/thisroot.sh" ]; then source /usr/local/bin/thisroot.sh; fi
          export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          
          echo "Building..."
          cmake --build build -j"$(nproc)" --verbose

      - name: Test
        run: |
          # Source environment again  
          if [ -f "/opt/detector/setup.sh" ]; then source /opt/detector/setup.sh; fi
          if [ -f "/opt/software/setup.sh" ]; then source /opt/software/setup.sh; fi
          if [ -f "/usr/local/bin/thisroot.sh" ]; then source /usr/local/bin/thisroot.sh; fi
          export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          
          echo "Running tests..."
          ctest --test-dir build --output-on-failure