name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eic/eic_ci:nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup EIC Environment
        run: |
          # Source any available environment setup scripts
          if [ -f "/opt/detector/setup.sh" ]; then
            source /opt/detector/setup.sh
          fi
          if [ -f "/opt/software/setup.sh" ]; then
            source /opt/software/setup.sh
          fi
          if [ -f "/usr/local/bin/thisroot.sh" ]; then
            source /usr/local/bin/thisroot.sh
          fi
          # Set up common EIC paths
          export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          # Print environment for debugging
          echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          # Check for available packages
          find /usr/local -name "*podio*" -o -name "*edm4hep*" | head -5 || echo "No podio/edm4hep found in /usr/local"
          find /opt -maxdepth 2 -name "*podio*" -o -name "*edm4hep*" | head -5 || echo "No podio/edm4hep found in /opt"

      - name: Configure
        run: |
          # Source environment again
          if [ -f "/opt/detector/setup.sh" ]; then source /opt/detector/setup.sh; fi
          if [ -f "/opt/software/setup.sh" ]; then source /opt/software/setup.sh; fi
          if [ -f "/usr/local/bin/thisroot.sh" ]; then source /usr/local/bin/thisroot.sh; fi
          export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          # Source environment again
          if [ -f "/opt/detector/setup.sh" ]; then source /opt/detector/setup.sh; fi
          if [ -f "/opt/software/setup.sh" ]; then source /opt/software/setup.sh; fi
          if [ -f "/usr/local/bin/thisroot.sh" ]; then source /usr/local/bin/thisroot.sh; fi
          export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          cmake --build build -j"$(nproc)"

      - name: Test
        run: |
          # Source environment again  
          if [ -f "/opt/detector/setup.sh" ]; then source /opt/detector/setup.sh; fi
          if [ -f "/opt/software/setup.sh" ]; then source /opt/software/setup.sh; fi
          if [ -f "/usr/local/bin/thisroot.sh" ]; then source /usr/local/bin/thisroot.sh; fi
          export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          ctest --test-dir build --output-on-failure